spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/SpringBoot-JPA2
    username: root
    password: toor
    driver-class-name: org.h2.Driver

  jpa:    hibernate:      ddl-auto: create
    show-sql: true


logging:  level:    org.hibernaete.SQL: debug
    org.hibernaete.type: trace
    
    
spring.jpa.properties.hibernate.format_sql : true